### ISSUE TITLE
Mura plugin moved

### ISSUE THREAD

**Issue by marbetschar** [oarevalo/BugLogHQ#124]
Hi!

We moved the mura plugin for your BugLogHQ over to RIAForge:
http://murabugloghq.riaforge.org

Also my website address has changed to the following:
http://marco.betschart.name

Would be happy if you can adjust the links on the BugLogHQ website accordingly :)

**Comment by oarevalo** [comment]
Hi, the bugloghq.com website is updated.

Thanks!

**Comment by marbetschar** [comment]
Perfect! Thank you!!!
