### ISSUE TITLE
Mobile link not working

### ISSUE THREAD

**Issue by guillermoares** [oarevalo/BugLogHQ#125]
The "Mobile" link at the bottom of the web client redirects to "/buglog/mobile", which return a 404. At first, I thought that the problem was related to a missing "/" at the end, but "/buglog/mobile/" leads to a buggy page instead of the mobile web client.

**Comment by oarevalo** [comment]
It should work with or without the trailing "/", but it may depend on your setup. What do you mean by "buggy page"? can you provide a bit more detail?

**Comment by guillermoares** [comment]
Hmm... When I don't use the "/" I get 404. This also happens when I try to access [mysite]\buglog. If I don't append "/", I get 404 instead of the desktop login screen. I'm attaching a screenshot of the "buggy page".

I am using the latest Railo release, which is using Tomcat 7. I'm a newbie with this technologies, so I wouldn't be surprised if I'm missing some config step, but I've been going back and forward over the documentation and I couldn't find what I'm doing wrong. I'm guessing that there is some problem related to url mappings, but I can't figure out how to fix it.

![blhq - link to mobile](https://cloud.githubusercontent.com/assets/2014343/9827638/7f3dac06-58ba-11e5-8164-18392ddaee2b.png)
![buggy mobile page](https://cloud.githubusercontent.com/assets/2014343/9827669/bdc55212-58ba-11e5-870e-d0442ec85a2f.jpg)

**Comment by oarevalo** [comment]
The mobile page does look like its missing the assets (images, styles, etc). Can you try changing your directory to be "bugLog" instead? What OS and webserver are you using?

**Comment by guillermoares** [comment]
I think that the folder is already named "bugLog", with a capital "L", but let me see if I can connect to the server from home (I'm not at work right now). 

The OS is Windows Server 2003. I'm not sure what the web server is... I installed the latest version of Railo for Windows and nothing else, so I'm guessing that it camed bundled with Railo. I can see that Railo uses Tomcat and IIS. Not sure if they are/include the web server.

**Comment by guillermoares** [comment]
Oh, actually, you can connect yourself to the server if you want to see what's happening directly... The URL is in the second screenshot I gave before :S

**Comment by guillermoares** [comment]
Meh, I can't connect from here, I can't remember the user name. Anyway, I also had a buglog running localy and I had the same issue, although I did check the folder name to be "bugLog", so I don't think that's  the problem.

**Comment by oarevalo** [comment]
I am able to get to the login screen from my box to both the HQ and Mobile interfaces and both look fine. With and without the trailing /
Maybe a browser issue? I am using Chrome

**Comment by guillermoares** [comment]
Really? I'm using Chrome too and I'm also getting this problem from home... Let me try another browser, wait a sec...

**Comment by guillermoares** [comment]
I tried with Edge and IE 11 and had no luck :/... I'm getting 404 when I click the "mobile" link and the "buggy page" when I append the missing "/". Any idea what could this be? Did you try using my buglog URL?

**Comment by oarevalo** [comment]
I used this: 
http://216.108.235.106:8888/bugLog/mobile/
and 
http://216.108.235.106:8888/bugLog/mobile

Actually going without a trailing / redirects automatically to the /

**Comment by guillermoares** [comment]
Oh, now I see... I had to use the capital L in the URL too... But, strangely, the capital L seems to be necessary only when accesing the mobile interface. For example, this works fine:

http://216.108.235.106:8888/buglog/

but this doesn't:

http://216.108.235.106:8888/buglog/buglog
http://216.108.235.106:8888/buglog/mobile
http://216.108.235.106:8888/buglog/mobile/

Isn't it wierd? I totally discarded using the capital L in the URL because it was working fine without it when I tried to access the desktop interface.

Well... I guess this is fixed then. Feeling a little dumb here :P. Thank you very much for your help :). Would you mind removing my server addresses from the comments? I'm guessing that leaving them here is not exactly secure... Or may be remove the entire issue, since I'm not sure if it's really an issue. I'll remove the screenshot with the URL now.

Thanks again!

**Comment by oarevalo** [comment]
No problem! glad that you got it solved. Let me know if I can help in any way
