### ISSUE TITLE
We client showing wrong version number(?)

### ISSUE THREAD

**Issue by guillermoares** [oarevalo/BugLogHQ#126]
I see that the latest release is supposedly 1.8.5, but the web client shows 1.8.6 at the bottom of the screen.

**Comment by oarevalo** [comment]
It should say "BugLogMini 0.6", not 1.8.6. Can you include a screenshot of what you are seeing?

**Comment by guillermoares** [comment]
Here you go. I just noticed that it also says 1.8.6 in the login screen, so I'm sending you a screenshot of it.

I downloaded this version using the "Download Now" button in www.bugloghq.com, which redirects to RiaForge and, strangely, the download information displayed there states that the latest version is 1.8.2.
![bugloghq version](https://cloud.githubusercontent.com/assets/2014343/9827520/5988a520-58b9-11e5-9842-4599bc996251.jpg)

**Comment by oarevalo** [comment]
This has been updated on the buglog homepage, riaforge and github releases
page.

Thanks,

Oscar


On Fri, Sep 11, 2015 at 3:14 PM, guillermoares <notifications@github.com>
wrote:

> Here you go. I just noticed that it also says 1.8.6 in the login screen,
> so I'm sending you a screenshot of it.
>
> I downloaded this version using the "Download Now" button in
> www.bugloghq.com, which redirects to RiaForge and, strangely, the
> download information displayed there states that the latest version is
> 1.8.2.
> [image: bugloghq version]
> <https://cloud.githubusercontent.com/assets/2014343/9827520/5988a520-58b9-11e5-9842-4599bc996251.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oarevalo/BugLogHQ/issues/126#issuecomment-139672968>.
>



-- 
Oscar Arevalo
http://about.me/oarevalo
http://www.coldbricks.com - Content Management System
http://www.oscararevalo.com - My Blog
