### ISSUE TITLE
The ENTRYBEAN argument passed to the logEntry function is not of type rawEntryBean

### ISSUE THREAD

**Issue by KrunchMuffin** [oarevalo/BugLogHQ#131]
Ok I am going nuts trying to figure this out. I haven't changed anything, I don't think at least. At first it was this message in the validate method, so I stripped out and left return true since I don't use the APi key. Now I get it in logEntry. All the tests in the Utils pass.

**Comment by KrunchMuffin** [comment]
I have narrowed this down to something to do with the implementation I have. I have `stage` and `prod` on the same server. I have the stage bugloglistener pointing to the prod version. I only want the prod version to be the one that accepts the reports. Errors triggered on prod work fine, but on stage I get that error. What am I doing wrong in the config?

**Comment by oarevalo** [comment]
Stage and Prod are full copies of the Buglog code? or are you using the named instance approach? (i.e. only copy the config file)

**Comment by KrunchMuffin** [comment]
no, i am not using the named instance. was going to start however.

**Comment by oarevalo** [comment]
That might be the problem. BugLog uses the server scope to keep the "listener" instance, so 2 exact copies of the app may lead to some conflict.
Using named instances goes around this by assigning unique names to each listener reference on the server scope, thus avoiding any conflict.

**Comment by KrunchMuffin** [comment]
ahh..ok, let me try that and see what happens.

**Comment by KrunchMuffin** [comment]
so since I don't need the stage copy, if i remove it and point BL Listener to the prod version, should that not take care of it?

**Comment by KrunchMuffin** [comment]
ok, looks to be all sorted out now.

removed stage copy
have /buglog in admin mappings pointing to prod version
using buglog.listener.bugloglistenerWS

seems to be ok.

**Comment by oarevalo** [comment]
hmm, for example this is how a typical deploy would be:

```
/bugLog
  ...  (full app, with Production settings)
/dev
  Application.cfc
  /config
     buglog-config.xml.cfm   // alternate config (differnt dsn, etc)
  listener.cfc     // empty cfc that just  extends bugLog.listeners.bugLogListenerWS
  listener.cfm    // a cfinclude to /bugLog/listeners/bugLogListenerREST.cfm
```

any app that wants to use the `dev` instance will go directly to `/dev/listener.cfc` or `/dev/listener.cfm`

**Comment by KrunchMuffin** [comment]
is /dev inside Buglog or same level?

**Comment by oarevalo** [comment]
same level, but if you have the buglog full app deployed to the root, then /dev/ can also be inside

it doesnt matter where it is, as long as your paths in the includes/extends are adapted properly.

**Comment by KrunchMuffin** [comment]
ok, if I get some time I will try that. I don't really need to have multiple instances.
Thanks.

**Comment by oarevalo** [comment]
:+1: 
Please close the issue if everything is working as you expect.
Thanks!
