### ISSUE TITLE
Slack alert, no data sometimes?

### ISSUE THREAD

**Issue by KrunchMuffin** [oarevalo/BugLogHQ#134]
Any idea why this would happen? It's only sometimes and I can't figure out why.

![image](https://cloud.githubusercontent.com/assets/1037197/12325937/ac48cc1a-ba9b-11e5-913e-011dff7a3d87.png)

[slackAlert.cfc.txt](https://github.com/oarevalo/BugLogHQ/files/90468/slackAlert.cfc.txt)

**Comment by oarevalo** [comment]
I think the reason may be that you have a line"
```
 qry = oEntryFinder.search(argumentCollection = args)
```
But then it calls `sendEmail(qry, rawEntry);` without checking for the results of the search. So I guess even if the search does not find anything it will cause a notification to be sent.

In other words, if it doesn't exit on the "fail fast" conditions at the beginning of `processRule`, then it will send a notification for any other message; but the contents of the notification may be an empty recordset.

**Comment by KrunchMuffin** [comment]
thing is, I get an email as well with data and there is a bug logged.

**Comment by KrunchMuffin** [comment]
i switched it around to what the pushbullet one is using and seems better now.

**Comment by oarevalo** [comment]
Closing this ticket since it looks like the last suggestion worked. Feel free to open a new ticket if you have any issues
