### ISSUE TITLE
Exception Detail & ExtendedInfo

### ISSUE THREAD

**Issue by ivanionut** [oarevalo/BugLogHQ#141]
Excuse me Oscar, just one question:

it is normal that in the info error page (`bugLog/hq/index.cfm?event=entry&entryID=xxx`)
`Exception Detail` and `ExtendedInfo` are empty? 

:cold_sweat:

**Comment by oarevalo** [comment]
It could be, those fields are optional. Some ColdFusion exceptions (and also depending on how you throw them) may have empty `detail` field. The extendedInfo is also specific to how you notify BugLog of the error.
Are you explicitly passing them and seeing them empty?

**Comment by ivanionut** [comment]
ok, great ! Now I've seen it work with other types of errors.
