### ISSUE TITLE
A request was made to a resource that could not be located

### ISSUE THREAD

**Issue by Lukane415** [oarevalo/BugLogHQ#142]
Hi Oscar,
I´m having trouble with running BugLog for the first time.
I follow instalation instruction, placed BugLog to webroot, changed "general.externalURL" in config file to "/" but I´m still getting this error.
It seems like some problem with linking core files, but I´cant figure it out. 
I attach a screenshot, I hope it helps.
![buglog](https://cloud.githubusercontent.com/assets/17111618/14976916/22d2183a-1110-11e6-845b-6c456a4fff84.png)
When I try to access mobile version, I also get "A request was made to a resource that could not be located", during `<cfset application.appService = createObject("component","bugLog.components.hq.appService").init()>` call.

It´s running on apache 2.4, using OpenBD as CMFL interpreter + Jetty 8.1.
Any advice will be appreciated.

Have a nice day,
Lukáš

**Comment by Lukane415** [comment]
All is OK now, closing issue.

**Comment by oarevalo** [comment]
I'm glad that the issue is solved. What was the problem?

**Comment by Lukane415** [comment]
TBH, I have no idea.
I redid whole instalation once again (3rd or 4th time in total) and it worked :)
Works like a charm now, awesome tool, thanks :)

**Comment by oarevalo** [comment]
oh well, must have been the bugs of deploys past.

Let me know if you run into any other issues or have any questions.
