### ISSUE TITLE
stuck in queue?

### ISSUE THREAD

**Issue by jimpriest** [oarevalo/BugLogHQ#151]
I've set this up a few times before :) so I'm not sure what I've done wrong.

I'm using 1.8.7 (also tried 1.8.8), on MSSQL with FW/1.   I've got everything setup and a simple call in my setupRequest so it fires on every request (for testing).

Entries go into the queue but are never processed?  The BugLog service says it's running. But I have to either start/stop the service or manually go into the Service Monitor and hit 'process' for things to go into the system?

Haven't changed anything in the config other than database settings...

**Comment by oarevalo** [comment]
Hi Jim, I would start by checking that the scheduled tasks are in fact created. There should be at least one when the buglog service shows up as "running". The scheduled task is what reads the in memory queue and process the messages. It might also be that the task exists but is failing for some reason. You could try checking the CF logs and see if something jumps up.

**Comment by jimpriest** [comment]
Wasn't thinking - it was a local cert issue. Basically this:
https://groups.google.com/forum/#!topic/bugloghq/j5FoQp8E9E8
